import { prisma } from "../lib/prisma";

async function main() {
  console.log("Seeding sample clients...");

  const sampleClients = [
    {
      company: "ABC Technologies",
      tagline: "Technology Solutions for a Better Tomorrow",
      location: "San Francisco, USA",
      address: "123 Market Street, San Francisco, CA 94105, USA",
      website: "www.abctechnologies.com",
      email: "info@abctechnologies.com",
      phone: "+1 415 823 4567",
      industry: "Technology",
      companySize: "50–200 employees",
      status: "Active",
      contactName: "John Carter",
      contactRole: "CEO",
      contactEmail: "john@abctechnologies.com",
      contactImg: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
      revenue: 125000,
      outstanding: 25000,
      projectsCount: 3,
    },
    {
      company: "Global Tech Ltd.",
      tagline: "Global Enterprise IT & Cloud Solutions",
      location: "London, UK",
      address: "45 Canary Wharf, London, E14 5AB, UK",
      website: "www.globaltech.co.uk",
      email: "contact@globaltech.co.uk",
      phone: "+44 7700 900123",
      industry: "IT Services",
      companySize: "200–500 employees",
      status: "Active",
      contactName: "Sarah Mitchell",
      contactRole: "Managing Director",
      contactEmail: "sarah@globaltech.co.uk",
      contactImg: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80",
      revenue: 85000,
      outstanding: 15000,
      projectsCount: 2,
    },
    {
      company: "Skyline Media",
      tagline: "Creative Digital Marketing & Web Studio",
      location: "Toronto, Canada",
      address: "88 Bay Street, Toronto, ON M5J 2R8, Canada",
      website: "www.skylinemedia.ca",
      email: "hello@skylinemedia.ca",
      phone: "+1 416 555 0199",
      industry: "Marketing",
      companySize: "20–50 employees",
      status: "Active",
      contactName: "Emma Wilson",
      contactRole: "Founder",
      contactEmail: "emma@skylinemedia.ca",
      contactImg: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80",
      revenue: 45000,
      outstanding: 10000,
      projectsCount: 1,
    },
    {
      company: "BrightLink Solutions",
      tagline: "Advanced Industrial Automation & Systems",
      location: "Berlin, Germany",
      address: "Friedrichstraße 120, 10117 Berlin, Germany",
      website: "www.brightlink-solutions.de",
      email: "info@brightlink-solutions.de",
      phone: "+49 30 1234 5678",
      industry: "Manufacturing",
      companySize: "100–300 employees",
      status: "Active",
      contactName: "Michael Brown",
      contactRole: "Operations Head",
      contactEmail: "michael@brightlink-solutions.de",
      contactImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
      revenue: 210000,
      outstanding: 40000,
      projectsCount: 4,
    },
    {
      company: "NextGen Co.",
      tagline: "FinTech Platform & Real-Time Trading Software",
      location: "New York, USA",
      address: "Wall Street Plaza, New York, NY 10005, USA",
      website: "www.nextgenco.io",
      email: "support@nextgenco.io",
      phone: "+1 212 555 9820",
      industry: "Finance",
      companySize: "50–150 employees",
      status: "Active",
      contactName: "David Lee",
      contactRole: "CTO",
      contactEmail: "david@nextgenco.io",
      contactImg: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
      revenue: 90000,
      outstanding: 18000,
      projectsCount: 2,
    },
    {
      company: "Innovate Ltd.",
      tagline: "Healthcare AI & Clinical Research Tools",
      location: "Sydney, Australia",
      address: "200 George St, Sydney NSW 2000, Australia",
      website: "www.innovateltd.com.au",
      email: "contact@innovateltd.com.au",
      phone: "+61 2 9876 5432",
      industry: "Healthcare",
      companySize: "30–80 employees",
      status: "Inactive",
      contactName: "Sophia Garcia",
      contactRole: "CEO",
      contactEmail: "sophia@innovateltd.com.au",
      contactImg: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80",
      revenue: 38000,
      outstanding: 0,
      projectsCount: 1,
    },
    {
      company: "Core Systems",
      tagline: "Higher Education Portals & LMS Solutions",
      location: "Dubai, UAE",
      address: "Dubai Internet City, Building 3, Dubai, UAE",
      website: "www.coresystems.ae",
      email: "hello@coresystems.ae",
      phone: "+971 4 123 4567",
      industry: "Education",
      companySize: "300–800 employees",
      status: "Active",
      contactName: "Daniel Kim",
      contactRole: "Director",
      contactEmail: "daniel@coresystems.ae",
      contactImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
      revenue: 320000,
      outstanding: 65000,
      projectsCount: 5,
    },
    {
      company: "FutureWorks",
      tagline: "Commercial Property Asset Management Software",
      location: "Singapore",
      address: "1 Raffles Place, #20-01, Singapore 048616",
      website: "www.futureworks.sg",
      email: "info@futureworks.sg",
      phone: "+65 6789 0123",
      industry: "Real Estate",
      companySize: "80–200 employees",
      status: "Active",
      contactName: "Olivia Martinez",
      contactRole: "Owner",
      contactEmail: "olivia@futureworks.sg",
      contactImg: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80",
      revenue: 75000,
      outstanding: 12000,
      projectsCount: 2,
    },
    {
      company: "Vector Inc.",
      tagline: "Global Supply Chain Tracking & Telematics",
      location: "Tokyo, Japan",
      address: "Roppongi Hills Mori Tower, Tokyo, Japan",
      website: "www.vector-inc.jp",
      email: "support@vector-inc.jp",
      phone: "+81 3 5555 1234",
      industry: "Logistics",
      companySize: "150–400 employees",
      status: "Active",
      contactName: "James Anderson",
      contactRole: "CEO",
      contactEmail: "james@vector-inc.jp",
      contactImg: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
      revenue: 110000,
      outstanding: 20000,
      projectsCount: 3,
    },
    {
      company: "Prime Digital",
      tagline: "Omnichannel Retail & Headless Commerce",
      location: "Paris, France",
      address: "15 Rue de la Paix, 75002 Paris, France",
      website: "www.primedigital.fr",
      email: "bonjour@primedigital.fr",
      phone: "+33 1 42 68 55 00",
      industry: "E-commerce",
      companySize: "40–90 employees",
      status: "Prospect",
      contactName: "Isabella Thomas",
      contactRole: "Founder",
      contactEmail: "isabella@primedigital.fr",
      contactImg: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80",
      revenue: 50000,
      outstanding: 15000,
      projectsCount: 1,
    },
  ];

  for (const c of sampleClients) {
    await prisma.client.create({
      data: c,
    });
  }

  console.log(`Seeded ${sampleClients.length} clients successfully.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
